"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { useRouter, useParams } from "next/navigation";
import { getResumeById, updateResume } from "@/lib/resumeService";

interface ResumeData {
  title: string;
  name: string;
  email: string;
  phone: string;
  summary: string;
  experience: string;
  education: string;
  skills: string;
}

export default function ResumeEditor() {
  const [resume, setResume] = useState<ResumeData | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [atsScore, setAtsScore] = useState(0);
  const router = useRouter();
  const params = useParams();
  const resumeId = params.id as string;

  useEffect(() => {
    checkUser();
    if (resumeId) {
      loadResume();
    }
  }, [resumeId]);

  async function checkUser() {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      router.push("/login");
    }
  }

  async function loadResume() {
    try {
      const data = await getResumeById(resumeId);
      setResume(data.content);
      setAtsScore(data.ats_score || 0);
    } catch (error) {
      console.error('Error loading resume:', error);
      router.push('/dashboard');
    } finally {
      setLoading(false);
    }
  }

  const calculateATSScore = (data: ResumeData) => {
    let score = 0;
    if (data?.name && data.name.length > 2) score += 15;
    if (data?.email && data.email.includes('@')) score += 15;
    if (data?.summary && data.summary.length > 50) score += 20;
    if (data?.experience && data.experience.length > 100) score += 25;
    if (data?.education && data.education.length > 50) score += 15;
    if (data?.skills && data.skills.split(',').length > 3) score += 10;
    return score;
  };

  const handleInputChange = (field: keyof ResumeData, value: string) => {
    if (resume) {
      const newData = { ...resume, [field]: value };
      setResume(newData);
      setAtsScore(calculateATSScore(newData));
    }
  };

  async function handleSave() {
    if (!resume) return;
    setSaving(true);
    try {
      const newScore = calculateATSScore(resume);
      await updateResume(resumeId, resume.title, resume, newScore);
      setAtsScore(newScore);
      alert('Resume saved successfully!');
    } catch (error) {
      console.error('Error saving resume:', error);
      alert('Error saving resume');
    } finally {
      setSaving(false);
    }
  }

  // PDF Export function
  const handleExportPDF = () => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${resume?.title || 'Resume'} - ${resume?.name || 'Untitled'}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px; }
          h1 { color: #333; border-bottom: 2px solid #9333ea; padding-bottom: 10px; }
          h2 { color: #555; margin-top: 20px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
          .contact { margin: 20px 0; padding: 10px; background: #f5f5f5; }
          .section { margin: 20px 0; }
          @media print { body { margin: 0; padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>${resume?.name || ''}</h1>
        <div class="contact">
          ${resume?.email ? `<div>📧 ${resume.email}</div>` : ''}
          ${resume?.phone ? `<div>📞 ${resume.phone}</div>` : ''}
        </div>
        ${resume?.summary ? `<div class="section"><h2>Professional Summary</h2><p>${resume.summary.replace(/\n/g, '<br/>')}</p></div>` : ''}
        ${resume?.experience ? `<div class="section"><h2>Work Experience</h2><div style="white-space: pre-line;">${resume.experience.replace(/\n/g, '<br/>')}</div></div>` : ''}
        ${resume?.education ? `<div class="section"><h2>Education</h2><div style="white-space: pre-line;">${resume.education.replace(/\n/g, '<br/>')}</div></div>` : ''}
        ${resume?.skills ? `<div class="section"><h2>Skills</h2><p>${resume.skills}</p></div>` : ''}
        <div style="margin-top: 40px; font-size: 12px; color: #999; text-align: center;">ATS Score: ${atsScore}% | Generated by ATS Resume Pro</div>
      </body>
      </html>
    `;
    
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    } else {
      alert('Please allow pop-ups to download PDF');
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-xl">Loading...</div>
      </div>
    );
  }

  if (!resume) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-xl">Resume not found</div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4">
        <div className="bg-white rounded-lg shadow-lg p-6">
          {/* Header with PDF button */}
          <div className="flex justify-between items-center mb-6">
            <h1 className="text-2xl font-bold">Edit Resume</h1>
            <div className="space-x-3">
              <button
                onClick={handleExportPDF}
                className="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition flex items-center gap-2"
              >
                📄 Download PDF
              </button>
              <button
                onClick={() => router.push('/dashboard')}
                className="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600"
              >
                Back
              </button>
            </div>
          </div>

          {/* ATS Score Display */}
          <div className="mb-6 p-4 bg-gradient-to-r from-purple-50 to-indigo-50 rounded-lg">
            <div className="flex justify-between items-center">
              <span className="font-semibold">ATS Score:</span>
              <span className="text-2xl font-bold text-purple-600">{atsScore}%</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-2 mt-2">
              <div 
                className="bg-purple-600 h-2 rounded-full transition-all duration-300"
                style={{ width: `${atsScore}%` }}
              />
            </div>
            <p className="text-sm text-gray-600 mt-2">
              {atsScore < 50 ? 'Your resume needs improvement' : 
               atsScore < 70 ? 'Good start! Add more details' : 
               atsScore < 90 ? 'Great! Almost there' :
               'Excellent! Your resume is ATS-friendly'}
            </p>
          </div>

          {/* ATS Suggestions Panel */}
          <div className="mb-6 p-4 bg-amber-50 border border-amber-200 rounded-lg">
            <h3 className="font-semibold text-amber-800 mb-3 flex items-center gap-2">
              <span>💡</span> Suggestions to Improve Your Score:
            </h3>
            <ul className="space-y-2">
              {(!resume.name || resume.name.length < 3) && 
                <li className="text-sm text-amber-800">• Add your full name at the top</li>}
              {(!resume.email || !resume.email.includes('@')) && 
                <li className="text-sm text-amber-800">• Add a valid email address</li>}
              {(!resume.summary || resume.summary.length < 50) && 
                <li className="text-sm text-amber-800">• Write a professional summary (50+ characters)</li>}
              {(!resume.experience || resume.experience.length < 100) && 
                <li className="text-sm text-amber-800">• Add detailed work experience (100+ characters)</li>}
              {resume.experience && !resume.experience.includes('•') && 
                <li className="text-sm text-amber-800">• Use bullet points (•) in your experience section</li>}
              {resume.experience && !resume.experience.match(/\d+%|\$|increased|improved|led|managed/i) && 
                <li className="text-sm text-amber-800">• Add metrics and achievements (%, $, numbers, action verbs)</li>}
              {(!resume.skills || resume.skills.split(',').length < 5) && 
                <li className="text-sm text-amber-800">• Add 5+ skills (comma-separated) relevant to your target job</li>}
              {(!resume.education || resume.education.length < 50) && 
                <li className="text-sm text-amber-800">• Add your education details (degree, institution, year)</li>}
            </ul>
            <div className="mt-3 pt-2 border-t border-amber-200 text-xs text-amber-600">
              💡 Tip: ATS systems scan for keywords - customize your resume for each job application
            </div>
          </div>

          {/* Resume Form */}
          <div className="space-y-4">
            <div>
              <label className="block text-gray-700 font-semibold mb-2">Resume Title</label>
              <input
                type="text"
                value={resume.title || ''}
                onChange={(e) => setResume({...resume, title: e.target.value})}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
              />
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Full Name</label>
              <input
                type="text"
                value={resume.name || ''}
                onChange={(e) => handleInputChange('name', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="John Doe"
              />
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Email</label>
              <input
                type="email"
                value={resume.email || ''}
                onChange={(e) => handleInputChange('email', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="john@example.com"
              />
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Phone</label>
              <input
                type="tel"
                value={resume.phone || ''}
                onChange={(e) => handleInputChange('phone', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="(123) 456-7890"
              />
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Professional Summary</label>
              <textarea
                value={resume.summary || ''}
                onChange={(e) => handleInputChange('summary', e.target.value)}
                rows={4}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="Experienced professional with 5+ years in..."
              />
              <p className="text-xs text-gray-500 mt-1">{resume.summary?.length || 0}/50+ characters</p>
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Work Experience</label>
              <textarea
                value={resume.experience || ''}
                onChange={(e) => handleInputChange('experience', e.target.value)}
                rows={5}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="Software Engineer, ABC Corp (2020-Present)&#10;• Led development of...&#10;• Improved performance by 30%..."
              />
              <p className="text-xs text-gray-500 mt-1">{resume.experience?.length || 0}/100+ characters • Use bullet points (•) and metrics</p>
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Education</label>
              <textarea
                value={resume.education || ''}
                onChange={(e) => handleInputChange('education', e.target.value)}
                rows={3}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="B.S. Computer Science, University Name (2015-2019)"
              />
              <p className="text-xs text-gray-500 mt-1">{resume.education?.length || 0}/50+ characters</p>
            </div>

            <div>
              <label className="block text-gray-700 font-semibold mb-2">Skills (comma-separated)</label>
              <input
                type="text"
                value={resume.skills || ''}
                onChange={(e) => handleInputChange('skills', e.target.value)}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                placeholder="JavaScript, React, Node.js, Python, SQL"
              />
              <p className="text-xs text-gray-500 mt-1">{resume.skills?.split(',').filter(s => s.trim()).length || 0}/5+ skills recommended</p>
            </div>
          </div>

          {/* Save Button */}
          <div className="mt-8 flex justify-end">
            <button
              onClick={handleSave}
              disabled={saving}
              className="bg-green-600 text-white px-6 py-2 rounded-lg hover:bg-green-700 disabled:bg-gray-400"
            >
              {saving ? 'Saving...' : 'Save Resume'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}